export type Language = 'en' | 'zh';

export const personalInfo = {
  fullName: 'MD Monjur A Alahi Atib',
  shortName: 'Atib',
  chineseName: '艾缇',
  emails: ['aitbzaman@gmail.com', 'jamanatib@qq.com', 'ls2303201@buaa.edu.cn'],
  primaryEmail: 'aitbzaman@gmail.com',
  phone: '+8613264910246',
  wechat: 'Atibjaman',
  location: 'Beijing, China',
  address: '29 Haidian Road, Haidian District, Beijing',
  addressZh: '北京市海淀区海淀路29号，北京航空航天大学',
  nationality: 'Bangladesh',
  dob: '2000',
  passport: 'A19237023',
    researchGate: 'https://www.researchgate.net/profile/Monjur-A-Alahi-Atib',
  googleScholar: 'https://scholar.google.com/citations?view_op=list_works&hl=en&user=mWzQf5UAAAAJ',
  linkedIn: 'https://www.linkedin.com/in/atib-zaman',
  github: 'https://github.com/AithJaman',
  cvPdfUrl: '/cv-atib.pdf',
};

export const institutions = {
  buaa: { name: 'Beihang University (BUAA)', nameZh: '北京航空航天大学', url: 'https://is.buaa.edu.cn/en/' },
  ctgu: { name: 'China Three Gorges University (CTGU)', nameZh: '三峡大学', url: 'https://eng.ctgu.edu.cn/' },
  akij: { name: 'Akij Engineering Institute', nameZh: 'Akij 工程学院', url: 'https://aeiag.edu.bd/' },
};

export const socialLinks = [
    { icon: 'Linkedin', href: 'https://www.linkedin.com/in/atib-zaman', label: 'LinkedIn' },
  { icon: 'BookOpen', href: 'https://www.researchgate.net/profile/Monjur-A-Alahi-Atib', label: 'ResearchGate' },
  { icon: 'GraduationCap', href: 'https://scholar.google.com/citations?user=mWzQf5UAAAAJ&hl=en', label: 'Google Scholar' },
  { icon: 'Github', href: 'https://github.com/AithJaman', label: 'GitHub' },
  { icon: 'Mail', href: 'mailto:aitbzaman@gmail.com', label: 'Email' },
];

export const siteConfig = {
  languages: ['en', 'zh'] as Language[],
  defaultLanguage: 'zh' as Language,
  title: { en: 'Atib | Automation & Control Engineer', zh: '艾缇 | 自动化与控制工程师' },
  description: { en: 'Portfolio of MD Monjur A Alahi Atib - Control Engineering, Automation & Research', zh: 'MD Monjur A Alahi Atib的作品集 - 控制工程、自动化与研究' },
};

export const navigationConfig = {
  logo: { en: 'Atib', zh: '艾缇' },
  links: [
    { label: { en: 'About', zh: '关于' }, href: '#about' },
    { label: { en: 'Skills', zh: '技能' }, href: '#skills' },
    { label: { en: 'Achievements', zh: '成就' }, href: '#achievements' },
    { label: { en: 'Projects', zh: '项目' }, href: '#projects' },
    { label: { en: 'Publications', zh: '论文' }, href: '#publications' },
    { label: { en: 'Education', zh: '教育' }, href: '#education' },
  ],
  contactLabel: { en: 'Contact', zh: '联系' },
  contactHref: '#contact',
};

export const heroConfig = {
  name: { en: 'ATIB', zh: '艾缇' },
  roles: { en: ['Control Engineer', 'Automation Specialist', 'Researcher', 'Developer'], zh: ['控制工程师', '自动化专家', '研究员', '开发者'] },
  backgroundImage: '/atib-portfolio/images/hero-bg.jpg',
  tagline: { en: 'Automation & Control Engineer | Researcher', zh: '自动化与控制工程师 | 研究员' },
  subtitle: { en: "Master's in Control Engineering at Beihang University (BUAA). Specializing in robust nonlinear control, airship dynamics, PLC-based automation, and AI for e-commerce. CSC Scholarship recipient with 2 IFAC publications.", zh: '北京航空航天大学控制工程硕士。专攻鲁棒非线性控制、飞艇动力学、PLC自动化及电商AI应用。中国政府奖学金获得者，发表2篇IFAC论文。' },
  badges: [
    { icon: '🏆', text: { en: 'CSC Scholar (2023-2026)', zh: 'CSC奖学金 (2023-2026)' } },
    { icon: '📄', text: { en: '2 IFAC Papers', zh: '2篇IFAC论文' } },
    { icon: '🔧', text: { en: 'CSWP | Six Sigma', zh: 'CSWP | 六西格玛' } },
    { icon: '🎓', text: { en: 'BUAA Researcher', zh: '北航研究员' } },
    { icon: '🌟', text: { en: 'Excellence Award (Tsinghua)', zh: '卓越奖 (清华大学)' } },
  ],
};

export const aboutConfig = {
  label: { en: 'About', zh: '关于' },
  description: { en: "Master's student in Control Engineering at Beihang University (BUAA), CSC Scholarship recipient. Published researcher in robust nonlinear control, airship dynamics, PLC automation and AI applications. Experienced in MATLAB/Simulink, SolidWorks (CSWP), Siemens PLC programming, and industrial control systems. Holder of Six Sigma Green Belt certification with 5 languages proficiency (Bengali, English, Chinese, Hindi, Urdu).", zh: '北京航空航天大学控制工程硕士，中国政府奖学金获得者。在鲁棒非线性控制、飞艇动力学、PLC自动化及AI应用领域有深入研究。精通MATLAB/Simulink、SolidWorks (CSWP)、西门子PLC编程和工业控制系统。持有六西格玛绿带认证，熟练掌握5种语言（孟加拉语、英语、中文、印地语、乌尔都语）。' },
  experienceValue: '6+',
  experienceLabel: { en: 'Years of\nResearch &\nEngineering', zh: '年研究\n与工程\n经验' },
  stats: [
    { value: '2', label: { en: 'IFAC\nPublications', zh: 'IFAC\n论文' } },
    { value: '7+', label: { en: 'Major\nProjects', zh: '主要\n项目' } },
    { value: '5', label: { en: 'Core\nSkill Areas', zh: '核心\n技能领域' } },
    { value: '5', label: { en: 'Languages\nFluent', zh: '流利\n语言' } },
  ],
        images: [
          { src: '/atib-portfolio/images/about-2.png', alt: { en: 'Research Work', zh: '研究工作' } },
    { src: '/atib-portfolio/images/about-1.jpg', alt: { en: 'Professional Photo', zh: '职业照片' } },
    
    { src: '/atib-portfolio/images/about-3.png', alt: { en: 'Lab & Projects', zh: '实验室与项目' } },
    { src: '/atib-portfolio/images/about-4.jpg', alt: { en: 'Academic Life', zh: '学术生活' } },
    
    { src: '/atib-portfolio/images/about-7.jpg', alt: { en: 'Research Team', zh: '研究团队' } },
          { src: '/atib-portfolio/images/about-5.jpg', alt: { en: 'Automation Project', zh: '自动化项目' } },
  ],
};

export const skillsConfig = {
  label: { en: 'Technical Skills', zh: '技术技能' },
  heading: { en: 'Expertise &\nCapabilities', zh: '专业领域\n与能力' },
  description: { en: 'A multidisciplinary skill set spanning control theory, industrial automation, mechanical design, and artificial intelligence.', zh: '跨学科技能组合，涵盖控制理论、工业自动化、机械设计和人工智能。' },
  categories: [
    { title: { en: 'Control & Robotics', zh: '控制与机器人' }, icon: 'Cpu', skills: ['MATLAB/Simulink', 'SMC / Backstepping', 'PID / LQR / MPC', 'Robust Control', 'Nonlinear Dynamics', 'Monte Carlo Analysis'], image: '/atib-portfolio/images/service-1.jpg' },
   { title: { en: 'PLC & Automation', zh: 'PLC与自动化' }, icon: 'Settings', skills: ['Siemens LOGO! / S7-200', 'Ladder', 'Industrial Wiring', 'Relay Logic'], image: '/atib-portfolio/images/service-2.jpg' },
    { title: { en: 'Design & Simulation', zh: '设计与仿真' }, icon: 'Box', skills: ['SolidWorks (CSWP Certified)', 'AutoCAD', 'FEA / CFD', '3D Modeling', 'FEA Structural Analysis'], image: '/atib-portfolio/images/service-3.jpg' },
    { title: { en: 'Creative & Promotional Skills', zh: '创意与推广技能' }, icon: 'Palette', skills: ['Adobe Photoshop', 'Adobe Premiere Pro', 'Canva', 'Promotional Photo Editing', 'Promotional Video Editing'], image: '/atib-portfolio/images/service-4.jpg' },
  ],
};

export const achievementsConfig = {
  label: { en: 'Achievements', zh: '荣誉成就' },
  heading: { en: 'Awards &\nRecognition', zh: '奖项与\n荣誉' },
  description: { en: 'Click any certificate to view details and full resolution.', zh: '点击任意证书查看详情和高清版本。' },
  items: [
    {
      image: '/atib-portfolio/images/cert-buaa-excellent.png',
      title: { en: 'BUAA Excellent Student Award', zh: '北航优秀学生奖' },
      subtitle: { en: 'Beihang University, 2025', zh: '北京航空航天大学，2025' },
      description: { en: 'Awarded for outstanding academic performance and research contributions among all international students.', zh: '因在自动化科学与电气工程学院所有国际学生中表现优异的学业成绩和研究贡献而荣获优秀学生奖。' },
      year: '2025',
      certificateImage: '/atib-portfolio/images/cert-buaa-excellent.png',
    },
    {
      image: '/atib-portfolio/images/cert-tsinghua-iede.png',
      title: { en: 'Tsinghua IEDE Program', zh: '清华IEDE项目' },
      subtitle: { en: 'Innovation & Entrepreneurship, 2024', zh: '创新创业，2024' },
      description: { en: 'Completed the IEDE Global Program at Tsinghua University in innovation, entrepreneurship and digital economy.', zh: '完成清华大学IEDE全球项目，在创新、创业和数字经济战略方面获得实践经验。' },
      year: '2024',
      certificateImage: '/atib-portfolio/images/cert-tsinghua-iede.png',
    },
    {
      image: '/atib-portfolio/images/cert-NEDL-PLC.png',
      title: { en: 'PLC Automation Training', zh: 'PLC自动化培训' },
      subtitle: { en: 'NEDL Certificate, 2022', zh: 'NEDL证书，2022' },
      description: { en: 'Professional training in Programmable Logic Controller based industrial automation with Siemens S7-1200.', zh: '可编程逻辑控制器（PLC）工业自动化系统专业培训，包括西门子S7-1200和HMI界面设计。' },
      year: '2022',
      certificateImage: '/atib-portfolio/images/cert-NEDL-PLC.png',
    },
    {
      image: '/atib-portfolio/images/cert-ctgu-outstanding-grad.png',
      title: { en: 'Outstanding Graduate Award', zh: '优秀毕业生奖' },
      subtitle: { en: 'CTGU, Class of 2023', zh: '三峡大学，2023届' },
      description: { en: 'Honored for exceptional academic achievements, leadership in research activities, and contributions to the university.', zh: '因出色的学业成绩、科研活动中的领导能力以及对大学社区的贡献而荣获优秀毕业生称号。' },
      year: '2023',
      certificateImage: '/atib-portfolio/images/cert-ctgu-outstanding-grad.png',
    },
    {
      image: '/atib-portfolio/images/cert-ctgu-sci-fest.png',
      title: { en: 'Science Festival - 3rd Prize', zh: '科学节三等奖' },
      subtitle: { en: 'CTGU, 2020', zh: '三峡大学，2020' },
      description: { en: 'Designed a PLC-based kitchen fire prevention system reducing unattended stove fire risks by 70%.', zh: '设计了基于PLC的创新厨房防火系统，通过自动化定时和报警系统将无人看管炉灶火灾风险降低70%。' },
      year: '2020',
      certificateImage: '/atib-portfolio/images/cert-ctgu-sci-fest.png',
    },
    {
      image: '/atib-portfolio/images/cert-ctgu-engg-drawing.png',
      title: { en: 'Engineering Drawing Competition', zh: '工程制图竞赛' },
      subtitle: { en: 'CTGU, 2021', zh: '三峡大学，2021' },
      description: { en: 'Secured top position in CAD software, technical drawing standards, and precision engineering visualization.', zh: '在工程制图竞赛中获得优胜，展示了出色的CAD软件技能、技术制图标准和精密工程可视化能力。' },
      year: '2021',
      certificateImage: '/atib-portfolio/images/cert-ctgu-engg-drawing.png',
    },
    {
      image: '/atib-portfolio/images/cert-akij-world-vocational.png',
      title: { en: 'World Vocational Skills Competition', zh: '世界职业院校技能大赛' },
      subtitle: { en: 'Akij Institute, 2019', zh: 'Akij学院，2019' },
      description: { en: 'Represented Akij Engineering Institute showcasing expertise in industrial electrical systems and automation.', zh: '代表Akij工程学院参加世界职业院校技能大赛，展示工业电气系统和自动化方面的专业知识。' },
      year: '2019',
      certificateImage: '/atib-portfolio/images/cert-akij-world-vocational.png',
    },
  ],
};

export const portfolioConfig = {
  label: { en: 'Featured Projects', zh: '代表性项目' },
  heading: { en: 'Selected\nWorks', zh: '精选\n作品' },
  description: { en: 'A collection of projects showcasing expertise in control systems, automation, AI integration, and sustainable energy.', zh: '展示控制系统、自动化、AI集成和可持续能源专长的项目合集。' },
  projects: [
    // ==================== PANEL 1: 3 FEATURED PROJECTS (1x3) ====================
    // --- 1. Masters Thesis ---
    {
      title: { en: 'Vector-Thrust Semi-Indoor Airship', zh: '矢量推力半室内飞艇' },
      category: { en: 'Robust Control / MATLAB', zh: '鲁棒控制 / MATLAB' },
      year: '2025',
      image: '/atib-portfolio/images/projects/airship-poster.png',
      introduction: { en: 'Designed and validated a robust nonlinear control framework for a spherical semi-indoor airship for filming and monitoring applications.', zh: '设计并验证用于半室内飞艇 filming 和监控应用的鲁棒非线性控制框架。' },
      objective: { en: 'Develop a robust control system that improves 3-DOF trajectory tracking, disturbance rejection, and stability for a vector-thrust spherical airship.', zh: '开发鲁棒控制系统，改善矢量推力球形飞艇的三自由度轨迹跟踪、抗扰动性和稳定性。' },
      result: { en: 'Masters Thesis - IFAC 2025', zh: '硕士论文 - IFAC 2025' },
      outcome: { en: 'Achieved 86% reduction in peak tracking error. Novel control architecture with Monte Carlo validation under 2000+ wind scenarios.', zh: '峰值跟踪误差降低86%。新型控制架构在2000+次风况下蒙特卡洛验证。' },
      featured: true,
            link: 'https://doi.org/10.1016/j.ifacol.2025.11.545',
      detail: {
        shortDescription: { en: 'Designed and validated a robust nonlinear control framework for a spherical semi-indoor airship for filming and monitoring applications. The system combines vector-thrust propulsion, buoyancy-assisted flight, and Sliding Mode-Based Backstepping Control to achieve stable trajectory tracking under disturbances.', zh: '设计并验证用于半室内飞艇 filming 和监控应用的鲁棒非线性控制框架，结合矢量推力推进、浮力辅助飞行和滑模反步控制，实现扰动下的稳定轨迹跟踪。' },
        myRole: { en: 'Researcher / Control System Designer', zh: '研究员 / 控制系统设计师' },
        problem: { en: 'Semi-indoor airships are safe and low-noise, but accurate motion control is difficult because of nonlinear dynamics, airflow disturbances, sensor noise, actuator limitations, and model uncertainty.', zh: '半室内飞艇安全且低噪音，但由于非线性动力学、气流扰动、传感器噪声、执行器限制和模型不确定性，精确运动控制很困难。' },
        whatIDid: [
          { en: 'Designed the airship platform concept and vector-thrust configuration', zh: '设计飞艇平台概念和矢量推力配置' },
          { en: 'Developed nonlinear dynamic models for altitude and 3-DOF motion', zh: '开发高度和三自由度运动的非线性动力学模型' },
          { en: 'Built a MATLAB/Simulink simulation framework', zh: '构建MATLAB/Simulink仿真框架' },
          { en: 'Designed a Sliding Mode-Based Backstepping Controller (SMBSC)', zh: '设计滑模反步控制器(SMBSC)' },
          { en: 'Compared SMBSC with Backstepping Control (BSC) and Sliding Mode Control (SMC)', zh: '将SMBSC与反步控制(BSC)和滑模控制(SMC)进行比较' },
          { en: 'Validated performance using trajectory tracking, disturbance tests, and Monte Carlo robustness analysis', zh: '使用轨迹跟踪、扰动测试和蒙特卡洛鲁棒性分析验证性能' },
          { en: 'Used FEA and CFD results to support mechanical and aerodynamic design validation', zh: '使用FEA和CFD结果支持机械和气动设计验证' },
        ],
        toolsUsed: { en: 'MATLAB, Simulink, SolidWorks, CFD, FEA', zh: 'MATLAB、Simulink、SolidWorks、CFD、FEA' },
        skillsDemonstrated: { en: 'Control systems, nonlinear modeling, simulation, robustness analysis, trajectory tracking, mechanical design validation, data visualization, research writing', zh: '控制系统、非线性建模、仿真、鲁棒性分析、轨迹跟踪、机械设计验证、数据可视化、研究写作' },
        keyResults: [
          { en: 'Achieved stable 3-DOF trajectory tracking', zh: '实现稳定的三自由度轨迹跟踪' },
          { en: 'Improved disturbance rejection under external disturbances', zh: '在外部扰动下改善扰动抑制' },
          { en: 'Demonstrated stronger robustness compared with BSC and SMC', zh: '与BSC和SMC相比展示更强的鲁棒性' },
          { en: 'Validated the framework under sensor noise, uncertainty, and simulated semi-indoor operating conditions', zh: '在传感器噪声、不确定性和模拟半室内操作条件下验证框架' },
        ],
        images: [
          '/atib-portfolio/images/projects/airship/airship-cad-thruster.jpg',
          '/atib-portfolio/images/projects/airship/airship-cad-design.jpg',
          '/atib-portfolio/images/projects/airship/airship-fea-airship.png',
          '/atib-portfolio/images/projects/airship/airship-fea-thruster.png',
          '/atib-portfolio/images/projects/airship/airship-simulink-model.png',
          '/atib-portfolio/images/projects/airship/airship-trajectory-multiple.png',
          '/atib-portfolio/images/projects/airship/airship-overall-modeling.png',
          '/atib-portfolio/images/projects/airship/airship-stepresponse-comparison.png',
          '/atib-portfolio/images/projects/airship/airship-trajectory-3d.png',
        ],
        videos: [
          '/atib-portfolio/images/projects/airship/airship-video-1.mp4',
          '/atib-portfolio/images/projects/airship/airship-video-2.mp4',
        ],
      },
    },
    // --- 2. Bachelors Thesis ---
    {
      title: { en: 'Advanced Home Automation Based on PLC', zh: '基于PLC的先进智能家居自动化' },
      category: { en: 'Siemens LOGO! / Smart Home / Bachelor Thesis', zh: 'Siemens LOGO! / 智能家居 / 本科论文' },
      year: '2023',
      image: '/atib-portfolio/images/projects/homeauto/homeauto-poster.png',
      introduction: { en: 'Designed and simulated a PLC-based smart home automation system to improve energy efficiency, safety, security, and comfort in residential environments.', zh: '设计并仿真基于PLC的智能家居自动化系统，以提高住宅环境的能源效率、安全性、安防性和舒适性。' },
      objective: { en: 'To develop a PLC-based intelligent home control system that automates household functions and improves safety, convenience, and energy management.', zh: '开发基于PLC的智能家庭控制系统，实现家庭功能自动化，提高安全性、便利性和能源管理。' },
      result: { en: 'Bachelor Thesis, CTGU 2023', zh: '本科毕业论文，三峡大学 2023' },
      outcome: { en: 'Automated lighting, curtains, pump, HVAC, and security functions. Enhanced home safety using fire, smoke, gas, and CO2 detection.', zh: '实现照明、窗帘、水泵、暖通空调和安防功能自动化。使用火灾、烟雾、气体和二氧化碳检测增强家庭安全。' },
      featured: true,
      detail: {
        shortDescription: { en: 'Designed and simulated a PLC-based smart home automation system integrating lighting, curtains, water pump, HVAC, fire prevention, security, and garden watering with 15+ sensors using Siemens LOGO! PLC.', zh: '设计并仿真基于PLC的智能家居自动化系统，集成照明、窗帘、水泵、暖通空调、消防、安防和花园灌溉，使用西门子LOGO! PLC和15+传感器。' },
        myRole: { en: 'Automation System Designer / PLC Programmer', zh: '自动化系统设计师 / PLC程序员' },
        problem: { en: 'Traditional home systems require manual control and may waste energy or respond slowly to safety risks such as fire, gas leakage, smoke, and unauthorized access.', zh: '传统家庭系统需要手动控制，可能浪费能源或对火灾、气体泄漏、烟雾和未经授权进入等安全风险的响应缓慢。' },
        whatIDid: [
          { en: 'Designed PLC logic for lighting, curtains, water pump, HVAC, and garden watering', zh: '设计照明、窗帘、水泵、暖通空调和花园灌溉的PLC逻辑' },
          { en: 'Integrated sensors for smoke, gas, CO2, temperature, humidity, motion, and human presence', zh: '集成烟雾、气体、二氧化碳、温度、湿度、运动和人体存在传感器' },
          { en: 'Developed fire detection, alarm, ventilation, and emergency water-spray safety logic', zh: '开发火灾检测、报警、通风和紧急喷水安全逻辑' },
          { en: 'Built security control using door/window detection, motion sensing, alarm, and CCTV trigger', zh: '使用门窗检测、运动感应、报警和监控触发构建安防控制' },
          { en: 'Created PLC ladder diagrams and hardware connection layouts', zh: '创建PLC梯形图和硬件连接布局' },
          { en: 'Simulated and validated the control process using LOGO! Soft Comfort', zh: '使用LOGO! Soft Comfort仿真和验证控制过程' },
        ],
        toolsUsed: { en: 'LOGO! Soft Comfort, Siemens LOGO! PLC, AutoCAD, Sensors, Relays', zh: 'LOGO! Soft Comfort、西门子LOGO! PLC、AutoCAD、传感器、继电器' },
        skillsDemonstrated: { en: 'PLC programming, automation design, sensor integration, relay control, smart home systems, electrical wiring design, safety-system logic', zh: 'PLC编程、自动化设计、传感器集成、继电器控制、智能家居系统、电气布线设计、安全系统逻辑' },
        keyResults: [
          { en: 'Automated lighting, curtains, pump, HVAC, and security functions', zh: '实现照明、窗帘、水泵、暖通空调和安防功能自动化' },
          { en: 'Improved energy saving through sensor-based control', zh: '通过基于传感器的控制改善节能效果' },
          { en: 'Enhanced home safety using fire, smoke, gas, and CO2 detection', zh: '使用火灾、烟雾、气体和二氧化碳检测增强家庭安全' },
          { en: 'Designed a scalable PLC-based system for smart home applications', zh: '设计可扩展的基于PLC的智能家居应用系统' },
        ],
        images: [
          '/atib-portfolio/images/projects/homeauto/homeauto-poster.png',
          '/atib-portfolio/images/projects/homeauto/homeauto-hvac.jpg',
          '/atib-portfolio/images/projects/homeauto/homeauto-kitchens.jpg',
          '/atib-portfolio/images/projects/homeauto/homeauto-kitchen2.jpg',
          '/atib-portfolio/images/projects/homeauto/homeauto-lightcontrol.jpg',
          '/atib-portfolio/images/projects/homeauto/homeauto-ladder1.jpg',
          '/atib-portfolio/images/projects/homeauto/homeauto-ladder2.jpg',
          '/atib-portfolio/images/projects/homeauto/homeauto-ladder3.jpg',
          '/atib-portfolio/images/projects/homeauto/homeauto-ladder4.jpg',
          '/atib-portfolio/images/projects/homeauto/homeauto-ladder5.jpg',
          '/atib-portfolio/images/projects/homeauto/homeauto-ladder6.jpg',
          '/atib-portfolio/images/projects/homeauto/homeauto-ladder7.jpg',
        ],
      },
    },
        // --- 3. 10kW Solar Power Plant (Featured) ---
    {
      title: { en: '10 kW Residential Solar Power Plant', zh: '10kW住宅太阳能电站' },
      category: { en: 'Renewable Energy / PSIM / Design', zh: '可再生能源 / PSIM / 设计' },
      year: '2023',
      image: '/atib-portfolio/images/projects/solar/solar-poster.png',
      introduction: { en: 'Designed and analyzed a 10 kW residential solar power plant for domestic energy generation, focusing on load calculation, inverter and battery sizing, solar panel selection, cost savings, and carbon-emission reduction.', zh: '设计并分析10kW住宅太阳能电站用于家庭发电，重点关注负载计算、逆变器和电池选型、太阳能电池板选择、成本节约和碳减排。' },
      objective: { en: 'To design a cost-efficient domestic solar power system that can reduce electricity bills and support sustainable energy use.', zh: '设计具有成本效益的家庭太阳能系统，可以减少电费并支持可持续能源使用。' },
      result: { en: 'New Energy Project, CTGU 2023', zh: '新能源项目，三峡大学 2023' },
      outcome: { en: 'Designed a 10kW domestic solar system with 24 panels of 415W each. Estimated long-term savings of about 241,498 RMB over 25 years with significant carbon reduction.', zh: '设计10kW家庭太阳能系统，使用24块415W太阳能电池板。估计25年长期节省约241,498元人民币，显著减少碳排放。' },
      featured: true,
      detail: {
        shortDescription: { en: 'Designed and analyzed a complete 10 kW residential solar power plant including load calculation, inverter and battery sizing, panel selection, PSIM simulation, and 25-year economic analysis.', zh: '设计并分析完整的10kW住宅太阳能电站，包括负载计算、逆变器和电池选型、电池板选择、PSIM仿真和25年经济分析。' },
        myRole: { en: 'Renewable Energy System Designer / Project Analyst', zh: '可再生能源系统设计师 / 项目分析师' },
        problem: { en: 'Rising electricity costs and environmental concerns drive the need for residential renewable energy solutions in communities with unreliable grid access.', zh: '电费上涨和环境问题推动了对电网不可靠的社区住宅可再生能源解决方案的需求。' },
        whatIDid: [
          { en: 'Calculated total household load demand', zh: '计算家庭总负载需求' },
          { en: 'Selected inverter capacity based on load requirement', zh: '根据负载需求选择逆变器容量' },
          { en: 'Estimated battery backup capacity', zh: '估算电池备用容量' },
          { en: 'Calculated solar panel requirement for a 10kW system', zh: '计算10kW系统的太阳能电池板需求' },
          { en: 'Analyzed 25-year cost savings and solar payback benefit', zh: '分析25年成本节约和太阳能回报收益' },
          { en: 'Simulated solar panel behavior using PSIM', zh: '使用PSIM仿真太阳能电池板行为' },
          { en: 'Evaluated cost efficiency and carbon-emission reduction potential', zh: '评估成本效率和碳减排潜力' },
        ],
        toolsUsed: { en: 'PSIM, Excel, Solar PV Design Calculations', zh: 'PSIM、Excel、太阳能光伏设计计算' },
        skillsDemonstrated: { en: 'Renewable energy design, load analysis, solar sizing, battery calculation, cost-benefit analysis, carbon reduction analysis, simulation', zh: '可再生能源设计、负载分析、太阳能选型、电池计算、成本效益分析、碳减排分析、仿真' },
        keyResults: [
          { en: 'Designed a 10kW domestic solar system', zh: '设计10kW家庭太阳能系统' },
          { en: 'Selected 24 solar panels of 415W each', zh: '选择24块415W太阳能电池板' },
          { en: 'Estimated long-term savings of about 241,498 RMB over 25 years', zh: '估计25年长期节省约241,498元人民币' },
          { en: 'Demonstrated potential reduction in electricity cost and carbon emissions', zh: '展示降低电费和碳排放的潜力' },
        ],
        images: [
          '/atib-portfolio/images/projects/solar/solar-poster.png',
        ],
      },
    },
    // ==================== PANEL 2: 6 PLC PROJECTS (2x3) ====================
    // --- 4. PLC Traffic Light ---
    {
      title: { en: 'PLC Traffic Light Control System', zh: 'PLC交通灯控制系统' },
      category: { en: 'PLC / STEP7 / Timing Control', zh: 'PLC / STEP7 / 定时控制' },
      year: '2023',
      image: '/atib-portfolio/images/projects/plc-traffic/traffic-poster.png',
      introduction: { en: 'Designed and programmed a PLC-based automatic traffic light control system for an intersection using timed sequencing and ladder logic.', zh: '使用定时排序和梯形图逻辑，设计并编程基于PLC的十字路口自动交通灯控制系统。' },
      objective: { en: 'To develop an automated PLC program that controls red, yellow, and green lights for north-south and east-west directions in a repeated cycle.', zh: '开发自动PLC程序，以重复周期控制南北和东西方向的红、黄、绿灯。' },
      result: { en: 'PLC Course Project', zh: 'PLC课程项目' },
      outcome: { en: 'Successfully automated intersection traffic light operation with repeated red-green-yellow signal cycles and start/stop control.', zh: '成功实现十字路口交通灯操作自动化，具有重复的红绿黄信号周期和启停控制。' },
      detail: {
        shortDescription: { en: 'Designed and programmed a PLC-based automatic traffic light control system for an intersection using timed sequencing, memory relay logic, and ladder logic in the STEP7 PLC environment.', zh: '在STEP7 PLC环境中，使用定时排序、存储器继电器逻辑和梯形图逻辑，设计并编程基于PLC的十字路口自动交通灯控制系统。' },
        myRole: { en: 'PLC Programmer / Automation System Developer', zh: 'PLC程序员 / 自动化系统开发人员' },
        problem: { en: 'Traffic intersections require accurate signal timing to manage vehicle flow safely and reduce manual control dependency.', zh: '十字路口需要准确的信号定时来安全管理车流并减少手动控制依赖。' },
        whatIDid: [
          { en: 'Designed traffic light timing logic using PLC function instructions', zh: '使用PLC功能指令设计交通灯定时逻辑' },
          { en: 'Programmed start/stop control using memory relay logic', zh: '使用存储器继电器逻辑编程启停控制' },
          { en: 'Used timers to control red, green, yellow, and flashing light sequences', zh: '使用定时器控制红、绿、黄和闪烁灯序列' },
          { en: 'Assigned PLC inputs and outputs for traffic signal modules', zh: '为交通信号模块分配PLC输入和输出' },
          { en: 'Simulated and tested the program in the STEP7 PLC environment', zh: '在STEP7 PLC环境中仿真和测试程序' },
        ],
        toolsUsed: { en: 'Siemens STEP7, PLC Experiment Box, Ladder Logic, Traffic Light Control Module', zh: '西门子STEP7、PLC实验箱、梯形图逻辑、交通灯控制模块' },
        skillsDemonstrated: { en: 'PLC programming, ladder logic, timer-based sequencing, automation control, debugging, input/output mapping', zh: 'PLC编程、梯形图逻辑、基于定时器的排序、自动化控制、调试、输入/输出映射' },
        keyResults: [
          { en: 'Successfully automated intersection traffic light operation', zh: '成功实现十字路口交通灯操作自动化' },
          { en: 'Implemented repeated red-green-yellow signal cycles', zh: '实现重复的红绿黄信号周期' },
          { en: 'Added start/stop control for system operation', zh: '添加系统操作的启停控制' },
          { en: 'Improved understanding of real-time PLC-based traffic automation', zh: '提高对基于PLC的实时交通自动化的理解' },
        ],
        images: [
          '/atib-portfolio/images/projects/plc-traffic/traffic-ladder1.jpg',
          '/atib-portfolio/images/projects/plc-traffic/traffic-ladder2.jpg',
          '/atib-portfolio/images/projects/plc-traffic/traffic-ladder3.jpg',
          '/atib-portfolio/images/projects/plc-traffic/traffic-ladder4.jpg',
          '/atib-portfolio/images/projects/plc-traffic/traffic-ladder5.jpg',
          '/atib-portfolio/images/projects/plc-traffic/traffic-ladder6.jpg',
          '/atib-portfolio/images/projects/plc-traffic/traffic-ladder7.jpg',
        ],
      },
    },
    // --- 5. PLC Material Mix ---
    {
      title: { en: 'PLC Material Mix Control System', zh: 'PLC物料混合控制系统' },
      category: { en: 'PLC / STEP7 / Process Control', zh: 'PLC / STEP7 / 过程控制' },
      year: '2023',
      image: '/atib-portfolio/images/projects/plc-mixing/mixing-poster.png',
      introduction: { en: 'Designed and programmed a PLC-based material mixing control system that automates feed pumps, mixer rotation, and discharge operation using sequential ladder logic.', zh: '设计并编程基于PLC的物料混合控制系统，使用顺序梯形图逻辑自动实现进料泵、混合器旋转和出料操作。' },
      objective: { en: 'To develop a PLC control program that automatically manages the full material mixing cycle, including feeding, mixing, reversing, and discharging.', zh: '开发PLC控制程序，自动管理完整的物料混合周期，包括进料、混合、反转和出料。' },
      result: { en: 'PLC Course Project', zh: 'PLC课程项目' },
      outcome: { en: 'Automated the complete material mixing sequence with correct feed-mix-reverse-discharge operation using timer and memory relay logic.', zh: '使用定时器和存储器继电器逻辑，实现完整的物料混合顺序自动化，具有正确的进料-混合-反转-出料操作。' },
      detail: {
        shortDescription: { en: 'Designed and programmed a PLC-based material mixing control system that automates feed pumps, mixer rotation, and discharge using sequential ladder logic with timers and memory relays.', zh: '设计并编程基于PLC的物料混合控制系统，使用带定时器和存储器继电器的顺序梯形图逻辑，实现进料泵、混合器旋转和出料自动化。' },
        myRole: { en: 'PLC Programmer / Automation System Developer', zh: 'PLC程序员 / 自动化系统开发人员' },
        problem: { en: 'Material mixing processes require accurate timing and proper operation sequences to ensure safe, consistent, and efficient production.', zh: '物料混合过程需要准确的定时和正确的操作顺序，以确保安全、一致和高效的生产。' },
        whatIDid: [
          { en: 'Programmed Feed Pump 1 and Feed Pump 2 to operate in sequence', zh: '编程进料泵1和进料泵2顺序运行' },
          { en: 'Designed timed mixer control for forward and reverse rotation', zh: '设计定时混合器控制，实现正转和反转' },
          { en: 'Added discharge valve control after the mixing cycle', zh: '在混合周期后添加出料阀控制' },
          { en: 'Used timers and memory relays to manage step-by-step process flow', zh: '使用定时器和存储器继电器管理逐步过程流程' },
          { en: 'Implemented start/stop logic so the system completes the current cycle before stopping', zh: '实现启停逻辑，使系统在停止前完成当前周期' },
          { en: 'Tested and debugged the PLC program for correct sequence operation', zh: '测试和调试PLC程序以确保正确的顺序操作' },
        ],
        toolsUsed: { en: 'Siemens STEP7, PLC Experiment Box, Ladder Logic, Material Mixing Control Module', zh: '西门子STEP7、PLC实验箱、梯形图逻辑、物料混合控制模块' },
        skillsDemonstrated: { en: 'PLC programming, ladder logic design, timer-based sequencing, process automation, motor control, industrial control logic, debugging', zh: 'PLC编程、梯形图逻辑设计、基于定时器的排序、过程自动化、电机控制、工业控制逻辑、调试' },
        keyResults: [
          { en: 'Automated the complete material mixing sequence', zh: '实现完整的物料混合顺序自动化' },
          { en: 'Ensured correct feed-mix-reverse-discharge operation', zh: '确保正确的进料-混合-反转-出料操作' },
          { en: 'Improved understanding of industrial batch-process automation', zh: '提高对工业批处理过程自动化的理解' },
          { en: 'Developed practical PLC control logic used in manufacturing and processing systems', zh: '开发制造和加工系统中使用的实用PLC控制逻辑' },
        ],
        images: [
          '/atib-portfolio/images/projects/plc-mixing/mixing-ladder1.jpg',
          '/atib-portfolio/images/projects/plc-mixing/mixing-ladder2.jpg',
          '/atib-portfolio/images/projects/plc-mixing/mixing-ladder3.jpg',
          '/atib-portfolio/images/projects/plc-mixing/mixing-ladder4.jpg',
          '/atib-portfolio/images/projects/plc-mixing/mixing-exp1.jpg',
          '/atib-portfolio/images/projects/plc-mixing/mixing-exp2.jpg',
        ],
      },
    },
    // --- 6. PLC Four-Stage Conveyor ---
    {
      title: { en: 'PLC Four-Stage Conveyor Belt', zh: 'PLC四级传送带控制' },
      category: { en: 'PLC / STEP7 / Conveyor Control', zh: 'PLC / STEP7 / 传送带控制' },
      year: '2023',
      image: '/atib-portfolio/images/projects/plc-conveyor/conveyor-poster.png',
      introduction: { en: 'Designed and programmed a PLC-based four-stage conveyor belt control system with sequential start-up, delayed shutdown, and fault-handling logic.', zh: '设计并编程基于PLC的四级传送带控制系统，具有顺序启动、延迟关闭和故障处理逻辑。' },
      objective: { en: 'To develop a PLC control program that starts four conveyor stages in order, manages delayed stopping, and responds correctly to simulated conveyor faults.', zh: '开发PLC控制程序，按顺序启动四级传送带，管理延迟停止，并对模拟的传送带故障做出正确响应。' },
      result: { en: 'PLC Course Project', zh: 'PLC课程项目' },
      outcome: { en: 'Automated four-stage conveyor start-up and shutdown with fault detection and staged stopping logic for industrial manufacturing applications.', zh: '实现四级传送带自动启停，具有故障检测和分级停止逻辑，用于工业制造应用。' },
      detail: {
        shortDescription: { en: 'Designed and programmed a PLC-based four-stage conveyor belt control system with sequential start-up, delayed shutdown, and fault-handling logic using timers, memory relays, and shift instructions.', zh: '使用定时器、存储器继电器和移位指令，设计并编程基于PLC的四级传送带控制系统，具有顺序启动、延迟关闭和故障处理逻辑。' },
        myRole: { en: 'PLC Programmer / Automation System Developer', zh: 'PLC程序员 / 自动化系统开发人员' },
        problem: { en: 'Industrial conveyor systems need proper sequencing and fault response to prevent material blockage, equipment damage, and unsafe operation.', zh: '工业传送带系统需要适当的排序和故障响应，以防止物料堵塞、设备损坏和不安全操作。' },
        whatIDid: [
          { en: 'Programmed four conveyor motors using PLC ladder logic', zh: '使用PLC梯形图逻辑编程四个传送带电机' },
          { en: 'Designed sequential start-up logic with 5-second delays', zh: '设计带5秒延迟的顺序启动逻辑' },
          { en: 'Developed delayed shutdown logic when the stop button is pressed', zh: '开发按下停止按钮时的延迟关闭逻辑' },
          { en: 'Added fault simulation using K1, K2, K3, and K4 switches', zh: '使用K1、K2、K3和K4开关添加故障模拟' },
          { en: 'Implemented different stop sequences for faults in each conveyor stage', zh: '为每个传送带阶段的故障实施不同的停止序列' },
          { en: 'Used timers, memory relays, and shift instructions for conveyor direction indication', zh: '使用定时器、存储器继电器和移位指令进行传送带方向指示' },
          { en: 'Tested and debugged the control sequence on the PLC experiment platform', zh: '在PLC实验平台上测试和调试控制序列' },
        ],
        toolsUsed: { en: 'Siemens STEP7, PLC Experiment Box, Ladder Logic, Four-Stage Conveyor Control Module', zh: '西门子STEP7、PLC实验箱、梯形图逻辑、四级传送带控制模块' },
        skillsDemonstrated: { en: 'PLC programming, ladder logic, conveyor automation, fault-handling logic, timer-based sequencing, motor control, industrial process control', zh: 'PLC编程、梯形图逻辑、传送带自动化、故障处理逻辑、基于定时器的排序、电机控制、工业过程控制' },
        keyResults: [
          { en: 'Automated four-stage conveyor start-up and shutdown sequence', zh: '实现四级传送带启停顺序自动化' },
          { en: 'Implemented fault detection and staged stopping logic', zh: '实施故障检测和分级停止逻辑' },
          { en: 'Improved understanding of conveyor control used in beverage and manufacturing industries', zh: '提高对饮料和制造业中使用的传送带控制的理解' },
          { en: 'Built practical experience in industrial automation and PLC debugging', zh: '建立工业自动化和PLC调试的实践经验' },
        ],
        images: [
          '/atib-portfolio/images/projects/plc-conveyor/conveyor-report.jpg',
          '/atib-portfolio/images/projects/plc-conveyor/conveyor-exp.jpg',
          '/atib-portfolio/images/projects/plc-conveyor/conveyor-ladder1.jpg',
          '/atib-portfolio/images/projects/plc-conveyor/conveyor-ladder2.jpg',
          '/atib-portfolio/images/projects/plc-conveyor/conveyor-ladder3.jpg',
          '/atib-portfolio/images/projects/plc-conveyor/conveyor-ladder4.jpg',
          '/atib-portfolio/images/projects/plc-conveyor/conveyor-ladder5.jpg',
          '/atib-portfolio/images/projects/plc-conveyor/conveyor-ladder6.jpg',
        ],
      },
    },
    // --- 7. PLC Water Tower ---
    {
      title: { en: 'PLC Water Tower Level Control', zh: 'PLC水塔水位控制' },
      category: { en: 'PLC / STEP7 / Level Control', zh: 'PLC / STEP7 / 液位控制' },
      year: '2023',
      image: '/atib-portfolio/images/projects/plc-water/water-poster.png',
      introduction: { en: 'Designed and implemented a PLC-based automatic water tower level control system that monitors water levels and controls tank filling using sensors, timers, indicators, and automated valve logic.', zh: '设计并实现基于PLC的自动水塔水位控制系统，使用传感器、定时器、指示灯和自动阀门逻辑监测水位并控制水箱注水。' },
      objective: { en: 'To develop an automated PLC control system that monitors tank water levels and controls the inlet valve and level indicators automatically.', zh: '开发自动PLC控制系统，监测水箱水位并自动控制进水阀和液位指示器。' },
      result: { en: 'PLC Course Project', zh: 'PLC课程项目' },
      outcome: { en: 'Automated water tank filling and stopping process with overflow prevention and dynamic liquid-level LED indication.', zh: '实现水箱注水和停止过程自动化，具有溢出预防和动态液位LED指示。' },
      detail: {
        shortDescription: { en: 'Designed and implemented a PLC-based automatic water tower level control system using sensors, timers, indicators, and automated valve logic with high/low level protection.', zh: '使用传感器、定时器、指示灯和自动阀门逻辑，设计并实现基于PLC的自动水塔水位控制系统，具有高低液位保护。' },
        myRole: { en: 'PLC Programmer / Industrial Automation Developer', zh: 'PLC程序员 / 工业自动化开发人员' },
        problem: { en: 'Manual water tank monitoring can lead to overflow, dry running, inefficient water usage, and unreliable water supply management.', zh: '手动水箱监测可能导致溢出、干转、低效用水和不可靠的供水管理。' },
        whatIDid: [
          { en: 'Designed PLC ladder logic for automatic water level monitoring', zh: '设计自动水位监测的PLC梯形图逻辑' },
          { en: 'Programmed water filling control using high-level and low-level sensors', zh: '使用高位和低位传感器编程注水控制' },
          { en: 'Integrated start/stop control and overflow protection logic', zh: '集成启停控制和溢出保护逻辑' },
          { en: 'Implemented sequential water level indication using indicator lights', zh: '使用指示灯实现顺序水位指示' },
          { en: 'Used timers, memory bits, and shift instructions for dynamic level simulation', zh: '使用定时器、存储位和移位指令进行动态液位仿真' },
          { en: 'Tested and debugged the PLC system using the experimental water tower module', zh: '使用实验水塔模块测试和调试PLC系统' },
        ],
        toolsUsed: { en: 'Siemens STEP7, PLC Experiment Box, Ladder Logic, Water Tower Control Module', zh: '西门子STEP7、PLC实验箱、梯形图逻辑、水塔控制模块' },
        skillsDemonstrated: { en: 'PLC programming, ladder logic, water level automation, sensor integration, timer control, industrial automation, process monitoring, debugging', zh: 'PLC编程、梯形图逻辑、水位自动化、传感器集成、定时器控制、工业自动化、过程监测、调试' },
        keyResults: [
          { en: 'Automated water tank filling and stopping process', zh: '实现水箱注水和停止过程自动化' },
          { en: 'Prevented overflow and low-water conditions', zh: '防止溢出和低水位情况' },
          { en: 'Simulated dynamic liquid-level changes using LED indicators', zh: '使用LED指示灯模拟动态液位变化' },
          { en: 'Improved understanding of industrial water management automation systems', zh: '提高对工业水管理自动化系统的理解' },
        ],
        images: [
          '/atib-portfolio/images/projects/plc-water/water-ladder1.jpg',
          '/atib-portfolio/images/projects/plc-water/water-ladder2.jpg',
          '/atib-portfolio/images/projects/plc-water/water-ladder3.jpg',
          '/atib-portfolio/images/projects/plc-water/water-ladder4.jpg',
          '/atib-portfolio/images/projects/plc-water/water-ladder5.jpg',
          '/atib-portfolio/images/projects/plc-water/water-ladder6.jpg',
          '/atib-portfolio/images/projects/plc-water/water-exp1.jpg',
          '/atib-portfolio/images/projects/plc-water/water-exp2.jpg',
        ],
      },
    },
    // --- 8. PLC Vending Machine ---
    {
      title: { en: 'PLC Vending Machine System', zh: 'PLC自动售货机系统' },
      category: { en: 'PLC / S7-200 / Simulation', zh: 'PLC / S7-200 / 仿真' },
      year: '2023',
      image: '/atib-portfolio/images/projects/plc-vending/vending-poster.png',
      introduction: { en: 'Designed and simulated a PLC-based vending machine system capable of automated product selection and dispensing using coin detection, relay-controlled motors, and dispensing mechanisms.', zh: '设计并仿真基于PLC的售货机系统，使用硬币检测、继电器控制电机和出货机构，实现自动产品选择和出货。' },
      objective: { en: 'To develop a PLC-based vending machine control system that integrates coin detection, product selection switches, relay-controlled motors, and dispensing mechanisms.', zh: '开发基于PLC的售货机控制系统，集成硬币检测、产品选择开关、继电器控制电机和出货机构。' },
      result: { en: 'CTGU Course Project 2023', zh: '三峡大学课程项目 2023' },
      outcome: { en: 'Successfully simulated automated vending operations with reliable dispensing logic using PLC timers and counters, integrating hardware and software control architecture.', zh: '成功仿真自动售货操作，使用PLC定时器和计数器实现可靠的出货逻辑，集成硬件和软件控制架构。' },
      detail: {
        shortDescription: { en: 'Designed and simulated a PLC-based vending machine system using Siemens S7-200 PLC and STEP7 MicroWIN SP9, integrating coin detection, product selection, relay-controlled motors, and dispensing mechanisms.', zh: '使用西门子S7-200 PLC和STEP7 MicroWIN SP9，设计并仿真基于PLC的售货机系统，集成硬币检测、产品选择、继电器控制电机和出货机构。' },
        myRole: { en: 'PLC Programmer / System Designer', zh: 'PLC程序员 / 系统设计师' },
        problem: { en: 'Manual vending operations are inefficient and lack coin validation, change calculation, and product tracking capabilities needed for modern retail environments.', zh: '手动售货操作效率低下，缺乏现代零售环境所需的硬币验证、找零计算和产品跟踪功能。' },
        whatIDid: [
          { en: 'Designed the PLC architecture with CPU 222 and I/O mapping for products', zh: '使用CPU 222设计PLC架构和产品I/O映射' },
          { en: 'Programmed coin detection and validation logic', zh: '编程硬币检测和验证逻辑' },
          { en: 'Built product selection switch input handling', zh: '构建产品选择开关输入处理' },
          { en: 'Designed relay-controlled motor dispensing mechanism', zh: '设计继电器控制电机出货机构' },
          { en: 'Created timer and counter-based automation logic', zh: '创建基于定时器和计数器的自动化逻辑' },
          { en: 'Simulated and validated using S7-200 Sim and STEP7 MicroWIN SP9', zh: '使用S7-200 Sim和STEP7 MicroWIN SP9进行仿真和验证' },
        ],
        toolsUsed: { en: 'Siemens S7-200, STEP7 MicroWIN SP9, S7-200 Sim, Ladder Logic, AutoCAD', zh: '西门子S7-200、STEP7 MicroWIN SP9、S7-200 Sim、梯形图逻辑、AutoCAD' },
        skillsDemonstrated: { en: 'PLC Programming, Industrial Automation, Ladder Logic Design, Motor and Relay Control, Electrical Wiring Design, System Simulation, Automation Logic Development', zh: 'PLC编程、工业自动化、梯形图逻辑设计、电机和继电器控制、电气布线设计、系统仿真、自动化逻辑开发' },
        keyResults: [
          { en: 'Successfully simulated automated vending operations', zh: '成功仿真自动售货操作' },
          { en: 'Implemented reliable dispensing logic using PLC timers and counters', zh: '使用PLC定时器和计数器实现可靠的出货逻辑' },
          { en: 'Integrated hardware and software control architecture', zh: '集成硬件和软件控制架构' },
          { en: 'Developed complete vending machine automation workflow', zh: '开发完整的售货机自动化工作流程' },
        ],
        images: [
          '/atib-portfolio/images/projects/plc-vending/vending-ladder1.jpg',
          '/atib-portfolio/images/projects/plc-vending/vending-ladder2.jpg',
          '/atib-portfolio/images/projects/plc-vending/vending-design1.jpg',
          '/atib-portfolio/images/projects/plc-vending/vending-design2.jpg',
        ],
      },
    },
        // --- 9. AI E-Commerce Content Automation ---
    {
      title: { en: 'AI E-Commerce Content Automation', zh: 'AI电商内容自动化' },
      category: { en: 'DeepSeek / PyTorch / FastAPI', zh: 'DeepSeek / PyTorch / FastAPI' },
      year: '2024',
      image: '/atib-portfolio/images/projects/ecommerce/ecommerce-poster.png',
      introduction: { en: 'Developed an AI-powered e-commerce content automation system that automatically identifies products from uploaded images, generates intelligent product captions, and recommends marketing hashtags for social media and online stores.', zh: '开发基于AI的电商内容自动化系统，自动识别上传图像中的产品，生成智能产品描述，并推荐社交媒体和在线商店的营销标签。' },
      objective: { en: 'To develop an AI-driven e-commerce assistant capable of automatically classifying products from images, generating product captions, suggesting relevant hashtags, and simplifying the product upload process for non-technical users.', zh: '开发AI驱动的电商助手，能够自动从图像分类产品、生成产品描述、建议相关标签，并简化非技术用户的产品上传流程。' },
      result: { en: 'Team Project - March 2025', zh: '团队项目 - 2025年3月' },
      outcome: { en: 'Reduced manual effort in product listing workflows. Improved automation in e-commerce content generation with a user-friendly AI-assisted upload interface.', zh: '减少产品列表工作流程中的手动工作量。通过用户友好的AI辅助上传界面改善电商内容生成自动化。' },
      detail: {
        shortDescription: { en: 'Developed an AI-powered e-commerce content automation system that automatically identifies products from uploaded images, generates intelligent product captions, and recommends marketing hashtags for social media and online stores. The system was designed to reduce manual effort in product listing workflows and improve product presentation efficiency.', zh: '开发基于AI的电商内容自动化系统，自动识别上传图像中的产品，生成智能产品描述，并推荐社交媒体和在线商店的营销标签。该系统旨在减少产品列表工作流程中的手动工作量并提高产品展示效率。' },
        myRole: { en: 'AI Application Developer / APK Builder / Frontend Integration Engineer', zh: 'AI应用开发者 / APK构建者 / 前端集成工程师' },
        problem: { en: 'E-commerce sellers spend significant time manually uploading products, writing captions, assigning categories, and creating hashtags for promotion. This repetitive workflow slows down product management and reduces efficiency, especially for small businesses and online sellers.', zh: '电商卖家花费大量时间手动上传产品、撰写描述、分配类别和创建促销标签。这种重复性工作流程减慢了产品管理速度并降低了效率，尤其是对小型企业和在线卖家而言。' },
        whatIDid: [
          { en: 'Developed and integrated the AI-based product upload workflow', zh: '开发并集成基于AI的产品上传工作流程' },
          { en: 'Built and debugged the mobile application (APK) for product automation', zh: '构建并调试用于产品自动化的移动应用程序(APK)' },
          { en: 'Designed the frontend UI using React.js and Tailwind CSS concepts', zh: '使用React.js和Tailwind CSS概念设计前端UI' },
          { en: 'Integrated AI outputs for product classification, caption generation, and hashtag recommendation', zh: '集成AI输出用于产品分类、描述生成和标签推荐' },
          { en: 'Worked on image upload, preview, and AI result display modules', zh: '开发图像上传、预览和AI结果显示模块' },
          { en: 'Helped structure the multi-task AI pipeline for image and text processing', zh: '帮助构建用于图像和文本处理的多任务AI流水线' },
          { en: 'Participated in testing, debugging, and interface optimization', zh: '参与测试、调试和界面优化' },
          { en: 'Contributed to technical documentation and project presentation preparation', zh: '为技术文档和项目演示准备工作做出贡献' },
        ],
        toolsUsed: { en: 'Python, React.js, Tailwind CSS, Flask, FastAPI, Deep Learning, Image Classification, NLP', zh: 'Python、React.js、Tailwind CSS、Flask、FastAPI、深度学习、图像分类、NLP' },
        skillsDemonstrated: { en: 'AI integration, frontend development, UI/UX design, APK deployment, deep learning workflow integration, image processing, caption generation, debugging, teamwork, technical documentation', zh: 'AI集成、前端开发、UI/UX设计、APK部署、深度学习工作流集成、图像处理、描述生成、调试、团队合作、技术文档' },
        keyResults: [
          { en: 'Reduced manual effort in product listing workflows', zh: '减少产品列表工作流程中的手动工作量' },
          { en: 'Improved automation in e-commerce content generation', zh: '改善电商内容生成自动化' },
          { en: 'Created a user-friendly AI-assisted upload interface', zh: '创建用户友好的AI辅助上传界面' },
          { en: 'Demonstrated multi-task AI functionality using image and text data', zh: '使用图像和文本数据演示多任务AI功能' },
          { en: 'Successfully integrated classification, captioning, and hashtag generation into a single workflow', zh: '成功将分类、描述和标签生成集成到单个工作流中' },
        ],
        images: [
          '/atib-portfolio/images/projects/ecommerce/ecommerce-poster.png',
        ],
      },
    },  ],
  cta: { label: { en: "Let's Collaborate", zh: '合作咨询' }, heading: { en: 'Have a project in mind?', zh: '有项目想法？' }, linkText: { en: 'Get in Touch', zh: '联系我' }, linkHref: '#contact' },
  viewAllLabel: { en: 'View All Projects', zh: '查看全部项目' },
};

export const publicationsConfig = {
  label: { en: 'Publications', zh: '学术论文' },
  heading: { en: 'Research\nPapers', zh: '研究\n论文' },
  description: { en: 'Peer-reviewed publications in leading control systems conferences (IFAC).', zh: '领先控制系统会议（IFAC）上的同行评审论文。' },
  items: [
    {
      authors: 'M. A. A. Atib, H. Ambreen, M. Imran, W. Lei',
      title: 'Dual-Gas H\u2082/He Airship Design: Optimized Buoyancy and PID-Based Altitude Control',
      journal: 'IFAC-PapersOnLine',
      details: 'vol. 59, no. 20, pp. 2567-2572',
      year: '2025',
            link: 'https://doi.org/10.1016/j.ifacol.2025.11.545',
      keywords: { en: 'Airship design, PID control, dual-gas buoyancy, altitude control', zh: '飞艇设计、PID控制、双气体浮力、高度控制' },
    },
    {
      authors: 'H. Ambreen, M. Imran, M. A. A. Atib, D. Tang',
      title: 'A Digital-Twin-Driven Modeling Approach for System Degradation and Remaining Useful Life Prediction',
      journal: 'IFAC-PapersOnLine',
      details: 'vol. 59, pp. 2177-2182',
      year: '2025',
            link: 'https://doi.org/10.1016/j.ifacol.2025.11.482',
      keywords: { en: 'Digital twin, degradation modeling, RUL prediction, prognostics', zh: '数字孪生、退化建模、剩余使用寿命预测、故障预测' },
    },
  ],
};

export const workExperienceConfig = {
  label: { en: 'Experience', zh: '工作经历' },
  heading: { en: 'Work &\nResearch', zh: '工作\n与研究' },
  description: { en: 'Professional experience spanning research, industry, and academic roles across three countries.', zh: '跨越三个国家的研究、工业和学术角色的专业经验。' },
  items: [
    {
      title: { en: 'Master Researcher', zh: '硕士研究员' },
      company: { en: 'Beihang University (BUAA)', zh: '北京航空航天大学' },
      period: '2023 - 2026',
      location: { en: 'Beijing, China', zh: '中国北京' },
      type: { en: 'Full-time Research', zh: '全职研究' },
      description: { en: 'Conducting research on robust nonlinear control systems for indoor airship applications. Developing Sliding Mode Backstepping Controllers (SMBSC) with Monte Carlo validation. Published 2 papers in IFAC conferences.', zh: '开展室内飞艇鲁棒非线性控制系统研究。开发带蒙特卡洛验证的滑模反步控制器(SMBSC)。在IFAC会议上发表2篇论文。' },
      achievements: [
        { en: 'Published 2 IFAC papers on airship control', zh: '发表2篇关于飞艇控制的IFAC论文' },
        { en: 'Achieved 86% peak error reduction vs conventional BSC', zh: '与传统BSC相比峰值误差降低86%' },
        { en: 'CSC Scholarship recipient', zh: '中国政府奖学金获得者' },
      ],
    },
    {
      title: { en: 'PLC Automation Intern', zh: 'PLC自动化实习生' },
      company: { en: 'National Engineering Development Ltd.', zh: '国家工程发展有限公司' },
      period: '2018 - 2019',
      location: { en: 'Gazipur, Bangladesh', zh: '孟加拉国加济布尔' },
      type: { en: 'Internship', zh: '实习' },
      description: { en: 'Hands-on experience with industrial PLC programming, electrical system design, and automation project implementation. Worked with Siemens S7-200 PLCs for manufacturing process control.', zh: '工业PLC编程、电气系统设计和自动化项目实施的实际经验。使用西门子S7-200 PLC进行制造过程控制。' },
      achievements: [
        { en: 'Programmed 8+ PLC experiments successfully', zh: '成功编程8+个PLC实验' },
        { en: 'Designed traffic light and elevator control systems', zh: '设计交通灯和电梯控制系统' },
        { en: 'Gained industrial wiring and SCADA experience', zh: '获得工业布线和SCADA经验' },
      ],
    },
  ],
};

export const documentsConfig = {
  label: { en: 'Documents', zh: '文档资料' },
  heading: { en: 'Transcripts &\nCertificates', zh: '成绩单\n与证书' },
  description: { en: 'Official academic transcripts, certificates, and scholarship documents available for download.', zh: '官方学术成绩单、证书和奖学金文件可供下载。' },
    items: [
    { title: { en: 'BSc Transcript', zh: '本科成绩单' }, file: 'bsc-transcript.pdf', size: '2.4 MB' },
    { title: { en: 'MSc Transcript', zh: '硕士成绩单' }, file: 'msc-transcript.pdf', size: '1.8 MB' },
    { title: { en: 'Bachelor Thesis', zh: '本科毕业论文' }, file: 'bachelor-thesis.pdf', size: '3.5 MB' },
    { title: { en: 'PLC Experiments Full Report', zh: 'PLC实验完整报告' }, file: 'plc-experiments-report.pdf', size: '4.2 MB' },
  ],
};

export const educationConfig = {
  label: { en: 'Education', zh: '教育背景' },
  heading: { en: 'Academic\nBackground', zh: '学术\n背景' },
  description: { en: 'A strong academic foundation in control engineering across three countries.', zh: '在三个国家建立的控制系统工程方面的扎实学术基础。' },
  items: [
    {
      degree: { en: 'M.Sc. in Control Engineering', zh: '控制工程硕士' },
      institution: 'Beihang University (BUAA)',
      institutionZh: '北京航空航天大学',
      institutionUrl: 'https://is.buaa.edu.cn/en/',
      period: '2023 - 2026',
      location: { en: 'Beijing, China', zh: '中国北京' },
      thesis: { en: 'Thesis: Design and Control of Vector-Thrust Spiral Indoor Airship for Semi-Indoor Filming and Surveillance', zh: '论文：半室内拍摄与监控的矢量推力螺旋室内飞艇设计与控制' },
      details: { en: 'Deep study of control theory, nonlinear systems, robust control, MATLAB/Simulink, SolidWorks, FPGA. Research focus: Robust & Nonlinear Control. CSC Scholarship.', zh: '深入学习控制理论、非线性系统、鲁棒控制、MATLAB/Simulink、SolidWorks、FPGA。研究方向：鲁棒与非线性控制。中国政府奖学金。' },
    },
    {
      degree: { en: 'B.Eng. in Automation', zh: '自动化本科' },
      institution: 'China Three Gorges University (CTGU)',
      institutionZh: '三峡大学',
      institutionUrl: 'https://eng.ctgu.edu.cn/',
      period: '2019 - 2023',
      location: { en: 'Yichang, China', zh: '中国宜昌' },
      thesis: { en: 'Thesis: Smart Home Automation System Based on PLC and Sensor Integration', zh: '论文：基于PLC和传感器集成的智能家居自动化系统' },
      details: { en: 'PLC programming, HMI/SCADA, sensors and actuators, microcontrollers, power electronics, industrial wiring, AutoCAD. CTGU Excellence Scholarship all 4 years.', zh: 'PLC编程、HMI/SCADA、传感器与执行器、微控制器、电力电子、工业布线、AutoCAD。连续四年获三峡大学卓越奖学金。' },
    },
    {
      degree: { en: 'Diploma in Electrical Technology', zh: '电气技术文凭' },
      institution: 'Akij Engineering Institute',
      institutionZh: 'Akij 工程学院',
      institutionUrl: 'https://aeiag.edu.bd/',
      period: '2016 - 2019',
      location: { en: 'Gazipur, Bangladesh', zh: '孟加拉国加济布尔' },
      thesis: { en: 'Focus: Industrial electrical systems, AC/DC motors, power systems', zh: '方向：工业电气系统、交直流电机、电力系统' },
      details: { en: 'Industrial electrical systems, AC/DC motors, power system analysis, circuit analysis, AutoCAD, Proteus simulation. Internship at NEDL (National Engineering Development Limited).', zh: '工业电气系统、交直流电机、电力系统分析、电路分析、AutoCAD、Proteus仿真。在NEDL（国家工程发展有限公司）实习。' },
    },
  ],
};

export const ctaConfig = {
  tags: { en: ['Control Engineer', 'Automation Specialist', 'Researcher'], zh: ['控制工程师', '自动化专家', '研究员'] },
  heading: { en: "Let's build something\ntogether", zh: '让我们一起\n构建未来' },
  description: { en: 'Open to collaborations in control systems, automation projects, and research partnerships.', zh: '欢迎控制系统、自动化项目和研究合作方面的合作。' },
  buttonText: { en: 'Call Now', zh: '立即致电' },
  buttonHref: 'tel:+8613264910246',
  email: 'aitbzaman@gmail.com',
  email2: 'jamanatib@qq.com',
  email3: 'ls2303201@buaa.edu.cn',
  wechat: 'Atibjaman',
  phone: '+8613264910246',
  backgroundImage: '/atib-portfolio/images/cta-bg.jpg',
};

export const footerConfig = {
  logo: { en: 'Atib', zh: '艾缇' },
  description: { en: 'Automation & Control Engineer passionate about building intelligent systems that bridge theory and practice. CSC Scholar at BUAA.', zh: '热衷于构建连接理论与实践的智能化系统的自动化与控制工程师。北航中国政府奖学金获得者。' },
  columns: [
    {
      title: { en: 'Navigation', zh: '导航' },
      links: [
        { label: { en: 'About', zh: '关于' }, href: '#about' },
        { label: { en: 'Skills', zh: '技能' }, href: '#skills' },
        { label: { en: 'Projects', zh: '项目' }, href: '#projects' },
        { label: { en: 'Publications', zh: '论文' }, href: '#publications' },
      ],
    },
        {
      title: { en: 'Resources', zh: '资源' },
      links: [
        { label: { en: 'Education', zh: '教育' }, href: '#education' },
        { label: { en: 'Contact', zh: '联系' }, href: 'tel:+8613264910246' },
        { label: { en: 'Download CV', zh: '下载简历' }, href: '/cv' },
      ],
    },
  ],
  socialLinks: [
    { iconName: 'Linkedin', href: 'https://www.linkedin.com/in/atib-zaman', label: 'LinkedIn' },
    { iconName: 'BookOpen', href: 'https://www.researchgate.net/profile/Monjur-A-Alahi-Atib', label: 'ResearchGate' },
    { iconName: 'GraduationCap', href: 'https://scholar.google.com/citations?view_op=list_works&hl=en&user=mWzQf5UAAAAJ', label: 'Google Scholar' },
    { iconName: 'Github', href: 'https://github.com/AithJaman', label: 'GitHub' },
    { iconName: 'Mail', href: 'mailto:aitbzaman@gmail.com', label: 'Email' },
  ],
  copyright: { en: '\u00A9 2026 MD Monjur A Alahi Atib. All rights reserved.', zh: '\u00A9 2026 MD Monjur A Alahi Atib. All rights reserved.' },
    credit: { en: '', zh: '' },
};
